### ISSUE TITLE
Problem with more sensors

### ISSUE THREAD

**Issue by serfer12** [Kirizaki/mysensors#3]
english follows
-------------------------------------------------------------------------------------------------------------------
Witam jeżeli dodaje więcej niż 31 przekaźników i podłączam Arduino do HomeAssistant 
to w logach HA pojawi się komunikat 
```
Gateway /dev/ttyUSB0 not ready after 15.0 secs so continuing with setup
```

w pliku `mysensor.json` pojaw się tylko  
`{}`
jeżeli dodam 31 przekaźników wszystko jest ok 

english:
-------------------------------------------------------------------------------------------------------------------
If I add more then 31 sensors and connect Arduino to HomeAssistant, there is a message in HA's log:
```
Gateway /dev/ttyUSB0 not ready after 15.0 secs so continuing with setup
```

in `mysensor.json` there is only:  
`{}`  

if there is only 31 sensors, everything is ok.

**Comment by Kirizaki** [comment]
Share your changes please

**Comment by serfer12** [comment]
https://megawrzuta.pl/download/d95b03baafae64d8bf82e4f6277a58f0.html

**Comment by Kirizaki** [comment]
Please follow:
1. Checkout `test_more_sensors_then_31`: https://github.com/th0m4sek/mysensors/tree/test_more_sensors_then_31
2. Build & flash Arduino with given sketch without changing anything
3. Remove old `mysensor.json` from HomeAssistant and reboot HomeAssistant

Result expected:  
HomeAssistant should show 34 sensors based on:  
```
std::vector<CustomSensor> customSensors = std::vector<CustomSensor>() = {
  { CustomSensor(SALOON_1_ID,       "Salon S1",       24) },
  { CustomSensor(SALOON_2_ID,       "Salon S2",       25) },
  { CustomSensor(SALOON_3_ID,       "Salon Lampka",   26) },
  { CustomSensor(GAMING_ROOM_1_ID,  "Gralnia S1",     27) },
  { CustomSensor(GAMING_ROOM_2_ID,  "Gralnia S2",     28) },
  { CustomSensor(BEDROOM_ID,        "Sypialnia",      29) },
  { CustomSensor(BED_1_ID,          "Lozko 1",        30) },
  { CustomSensor(BED_2_ID,          "Lozko 2",        31) },
  { CustomSensor(GUESTS_ID,         "Goscinny",       32) },
  { CustomSensor(BATHROOM_1_ID,     "Lazienka",       33) },
  { CustomSensor(BATHROOM_2_ID,     "Prysznic",       34) },
  { CustomSensor(MIRROR_ID,         "Lustro",         35) },
  { CustomSensor(FAN_ID,            "Wentylator",     36) },
  { CustomSensor(KITCHEN_1_ID,      "Kuchnia",        37) },
  { CustomSensor(KITCHEN_2_ID,      "Kuchnia ledy",   38) },
  { CustomSensor(KITCHEN_TABLE_ID,  "Kuchnia stolik", 39) },
  { CustomSensor(WORKSHOP_ID,       "Warsztat",       40) },
  { CustomSensor(CORRIDOR_ID,       "Korytarz",       41) },
  { CustomSensor(PUMP_ID,           "Pompa",          42) },
  { CustomSensor(HEATING_1_ID,      "Strefa 1",       43) },
  { CustomSensor(HEATING_2_ID,      "Strefa 2",       44) },
  { CustomSensor(HEATING_3_ID,      "Strefa 3",       45) },
  { CustomSensor(HEATING_4_ID,      "Strefa 4",       46) },
  { CustomSensor(HEATING_5_ID,      "Strefa 5",       47) },
  { CustomSensor(HEATING_6_ID,      "Strefa 6",       48) },
  { CustomSensor(HEATING_7_ID,      "Strefa 7",       49) },
  { CustomSensor(DUMMY_1_ID,        "Test 1",         49) },
  { CustomSensor(DUMMY_2_ID,        "Test 2",         49) },
  { CustomSensor(DUMMY_3_ID,        "Test 3",         49) },
  { CustomSensor(DUMMY_4_ID,        "Test 4",         49) },
  { CustomSensor(DUMMY_5_ID,        "Test 5",         49) },
  { CustomSensor(DUMMY_6_ID,        "Test 6",         49) },
  { CustomSensor(DUMMY_7_ID,        "Test 7",         49) },
  { CustomSensor(DUMMY_8_ID,        "Test 8",         49) }
};
```

How's the result?

**Comment by Kirizaki** [comment]
> https://megawrzuta.pl/download/d95b03baafae64d8bf82e4f6277a58f0.html

By the way, we will return to those changes. Right now let's focus on main problem `not working Arduino-HA with more then 31 sensors` and there are some other problems in your code.

**Comment by serfer12** [comment]
english follows
--------------------
Zgadza się Twój sketch działa na 34 
dzięki

english
--------------------
yours sketch is working fine with 31+ (e.g. 34) sensors

**Comment by Kirizaki** [comment]
No problem in code.
Cosing reason: wrong usage

**Comment by Kirizaki** [comment]
**Solution**: Do not duplicate `child_id`.
